"""Refine models relationship

Revision ID: 074ccbf948b4
Revises: 7a9950347298
Create Date: 2026-02-18 01:02:09.649520

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '074ccbf948b4'
down_revision: str | Sequence[str] | None = '7a9950347298'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add product_name to order_items and shipping_address to orders.

    Also adds order_id foreign key to reservations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('reservations', sa.Column('order_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_reservations_order_id', 'reservations', 'orders', ['order_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove product_name from order_items and shipping_address from orders.

    Also removes order_id foreign key from reservations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reservations_order_id', 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'order_id')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
