"""Add performance indexes

Revision ID: 2a03cc82fdc7
Revises: cdede027cf9b
Create Date: 2026-03-12 15:35:23.227561

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2a03cc82fdc7'
down_revision: str | Sequence[str] | None = 'cdede027cf9b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add performance indexes.

    No-op migration; indexes added in subsequent migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove performance indexes (no-op migration; no changes to rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
