"""add_b2b_api_keys

Revision ID: 58fabaa5d620
Revises: df8560c163db
Create Date: 2026-03-20 13:37:29.323173

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '58fabaa5d620'
down_revision: str | Sequence[str] | None = 'df8560c163db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the api_keys_b2b_partners table.

    Manages B2B API authentication keys.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'api_keys_b2b_partners',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('key_prefix', sa.String(length=12), nullable=False),
        sa.Column('hashed_key', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_api_keys_b2b_partners_key_prefix'),
        'api_keys_b2b_partners',
        ['key_prefix'],
        unique=False,
    )
    op.create_index(
        op.f('ix_api_keys_b2b_partners_user_id'),
        'api_keys_b2b_partners',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the api_keys_b2b_partners table and its indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_api_keys_b2b_partners_user_id'),
        table_name='api_keys_b2b_partners',
    )
    op.drop_index(
        op.f('ix_api_keys_b2b_partners_key_prefix'),
        table_name='api_keys_b2b_partners',
    )
    op.drop_table('api_keys_b2b_partners')
    # ### end Alembic commands ###
