"""make_price_non_nullable

Revision ID: 61a11ad734d2
Revises: 71e5495a30cd
Create Date: 2026-02-21 20:57:01.779744

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61a11ad734d2'
down_revision: str | Sequence[str] | None = '71e5495a30cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'price',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'price',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###
