"""empty message

Revision ID: 6a1398dbe560
Revises: e25c5de9bfe2
Create Date: 2026-02-21 22:13:07.532166

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '6a1398dbe560'
down_revision: str | Sequence[str] | None = 'e25c5de9bfe2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """No-op migration placeholder (empty migration with no schema changes)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """No-op rollback (empty migration with no changes to revert)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
