"""empty message

Revision ID: 8ca7fefa94b6
Revises: 6a1398dbe560
Create Date: 2026-02-22 14:04:03.870055

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '8ca7fefa94b6'
down_revision: str | Sequence[str] | None = '6a1398dbe560'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
