"""Add RBAC and Product status

Revision ID: 902cfb988689
Revises: 2a03cc82fdc7
Create Date: 2026-03-13 16:17:58.458310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '902cfb988689'
down_revision: str | Sequence[str] | None = '2a03cc82fdc7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add RBAC support.

    Creates user role and product status enums, adds role/is_verified/
    status columns, and removes is_superuser.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum(
        'ADMIN',
        'MODERATOR',
        'USER',
        'USER_B2B',
        'SELLER',
        'SELLER_B2B',
        name='userrole',
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)

    product_status_enum = sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatus')
    product_status_enum.create(op.get_bind(), checkfirst=True)

    # 1. Add as nullable
    op.add_column('products', sa.Column('status', product_status_enum, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', user_role_enum, nullable=True))

    # 2. Populate data
    op.execute("UPDATE products SET status = 'DRAFT'")
    op.execute('UPDATE users SET is_verified = FALSE')
    op.execute("UPDATE users SET role = 'USER'")

    # 3. Set NOT NULL
    op.alter_column('products', 'status', nullable=False)
    op.alter_column('users', 'is_verified', nullable=False)
    op.alter_column('users', 'role', nullable=False)

    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove RBAC columns and enums.

    Restores is_superuser column, drops role/is_verified/status columns.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_verified')
    op.drop_column('products', 'status')

    sa.Enum(name='productstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
