"""add_product_moderation_comment

Revision ID: 93c6bb315592
Revises: 96dda86ac1b0
Create Date: 2026-04-03 16:37:11.465877

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93c6bb315592'
down_revision: str | Sequence[str] | None = '96dda86ac1b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add moderation_comment column to products table.

    Stores moderator feedback.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('moderation_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove moderation_comment column from products table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'moderation_comment')
    # ### end Alembic commands ###
