"""add_verification_requests

Revision ID: 96dda86ac1b0
Revises: 58fabaa5d620
Create Date: 2026-03-21 21:39:51.747859

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96dda86ac1b0'
down_revision: str | Sequence[str] | None = '58fabaa5d620'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'verification_requests',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'target_role',
            postgresql.ENUM(
                'ADMIN',
                'MODERATOR',
                'USER',
                'USER_B2B',
                'SELLER',
                'SELLER_B2B',
                name='userrole',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'),
            nullable=False,
        ),
        sa.Column('docs_url', sa.JSON(), nullable=True),
        sa.Column('admin_feedback', sa.String(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_verification_requests_user_id'),
        'verification_requests',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_verification_requests_user_id'), table_name='verification_requests'
    )
    op.drop_table('verification_requests')
    # ### end Alembic commands ###
