"""Add performance indexes

Revision ID: cdede027cf9b
Revises: da065d87e52a
Create Date: 2026-03-12 15:35:08.784099

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdede027cf9b'
down_revision: str | Sequence[str] | None = 'da065d87e52a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add performance indexes on foreign key and frequently queried columns.

    Affects order_items, orders, and reservations tables.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False
    )
    op.create_index(
        op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(
        op.f('ix_reservations_expires_at'), 'reservations', ['expires_at'], unique=False
    )
    op.create_index(
        op.f('ix_reservations_order_id'), 'reservations', ['order_id'], unique=False
    )
    op.create_index(
        op.f('ix_reservations_product_id'), 'reservations', ['product_id'], unique=False
    )
    op.create_index(
        op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove performance indexes from order_items, orders, and reservations tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_product_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_order_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_expires_at'), table_name='reservations')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    # ### end Alembic commands ###
