"""add indexes to status and created_at fields

Revision ID: da065d87e52a
Revises: 2e443a9c1a0a
Create Date: 2026-03-11 19:12:37.293427

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da065d87e52a'
down_revision: str | Sequence[str] | None = '2e443a9c1a0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_reservations_created_at'),
        'reservations',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_reservations_status'),
        'reservations',
        ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_created_at'), table_name='reservations')
    # ### end Alembic commands ###
