"""add_moderation_statuses_and_moderator_id

Revision ID: df8560c163db
Revises: dd775d4f45bb
Create Date: 2026-03-19 15:22:29.774159

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df8560c163db'
down_revision: str | Sequence[str] | None = 'dd775d4f45bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('moderator_id', sa.Uuid(), nullable=True))
    op.create_index(
        op.f('ix_products_moderator_id'), 'products', ['moderator_id'], unique=False
    )
    op.create_index(
        op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False
    )
    op.create_foreign_key(
        'fk_products_moderator_id',
        'products',
        'users',
        ['moderator_id'],
        ['id'],
    )
    # ### end Alembic commands ###

    # Manual: Add new status values to the existing Enum
    op.execute("ALTER TYPE productstatus ADD VALUE 'PENDING_MODERATION'")
    op.execute("ALTER TYPE productstatus ADD VALUE 'MODERATION_IN_PROGRESS'")
    op.execute("ALTER TYPE productstatus ADD VALUE 'REJECTED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_moderator_id', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_index(op.f('ix_products_moderator_id'), table_name='products')
    op.drop_column('products', 'moderator_id')
    # ### end Alembic commands ###
