"""add OrderStatus param

Revision ID: e25c5de9bfe2
Revises: 61a11ad734d2
Create Date: 2026-02-21 21:52:47.386696

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e25c5de9bfe2'
down_revision: str | Sequence[str] | None = '61a11ad734d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """No-op migration placeholder.

    OrderStatus enum already created in prior migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """No-op rollback (no changes to revert)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
