name: CI init

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
# =====
# Hardcode will be replaced with secrets GitHub Repo
# =====
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: fairdrop_user
          POSTGRES_PASSWORD: fairdrop_password
          POSTGRES_DB: fairdrop_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd 'redis-cli ping'
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
# =====
# Hardcode will be replaced with secrets GitHub Repo
# =====
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up UV (without pip)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Check lint code
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest

      - name: Run mypy
        run: uv run mypy .
